---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: EnableGuestCheckout
flagType: boolean
description: "Enables the guest checkout"
labels:

availableValues:
  - "false"
  - "true"

isPermanent: false
