---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: EnableDarkMode
flagType: boolean
description: Enables dark mode
labels:

availableValues:
  - "false"
  - "true"

isPermanent: false
